---
engines:
  coffeelint:
    enabled: true
    checks:
      max_line_length:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
  eslint:
    enabled: true
  fixme:
    enabled: true
ratings:
  paths:
  - "**.coffee"
  - "**.js"
exclude_paths:
- .settings/
