steps:
  - plugin: Shell
    name: Install NVM
    command: 'curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash'
  - name: Install Node 7
    command: 'nvm install 7'
  - name: Install dependencies
    command: 'npm install'
  - name: Run tests
    command: 'npm test'
    
