steps:
  - plugin: Script
    name: Install NVM, Install dependencies, run tests
    command: |
    curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.32.1/install.sh | bash
    export NVM_DIR="/root/.nvm" && . "$NVM_DIR/nvm.sh"
    nvm install 7
    npm -g install npm@latest && npm install
    npm test   
