steps:
  - plugin: Script
    name: Install NVM, Install dependencies, run tests
    script: |
      apt-get update
      apt-get -y upgrade
      apt-get install build-essential libssl-dev
      npm install -g npm@latest
      npm install
      npm test   
