// Generated by CoffeeScript 1.12.0
(function() {
  var chai, expect, serialize;

  chai = require("chai");

  expect = chai.expect;

  serialize = require("../dist/serialize.js");

  describe("Serialization", function() {
    return it("should serialize a basic graph", function() {
      var obj, objb, objc;
      obj = {
        a: 1
      };
      objb = serialize.serialize(obj);
      objc = serialize.unserialize(objb);
      return expect(obj.a).to.equal(objc.a);
    });
  });

}).call(this);
